apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://your-kubernetes-api-url
    certificate-authority-data: YOUR_CA_CERTIFICATE
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
current-context: my-context
users:
- name: my-user
  user:
    token: YOUR_ACCESS_TOKEN





