apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://192.168.49.2:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
    certificate-authority-data: YOUR_CA_CERTIFICATE
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
current-context: my-context
users:
- name: my-user
  user:
    token: YOUR_ACCESS_TOKEN




