apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://192.168.49.2:8443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJek1EZ3lOakEyTkRRMU0xb1hEVE16TURneU5EQTJORFExTTFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEptClVLSnc3VnlWWUFvZ3BxaHYwVXVveUNITC9MMHozVHl6Wm9qNmdvYUlxOWNoV3JVSVlXNFVsRGlVUnJRVzE3K1cKdFFvRk45N1oxYi9talFheWozdUJJMUNMVHRuQnplOWhVZFoyV0pEZVlLVEtWRGV0ZTZXRVFaL2tWVUh0dWlEcgpNTzlXZEU0SHY0eTczc2E5bktRSlVOdE0zWStidUREOGQvTmNoS1VCbE5KbnFhbnpLU1VFOFFFQXBzN1FtWW0yCnVuYWtPSFl5WGJxdzI1Z3VOTzlJRDJSOFlUeEk0TlZWc3RZdi9nTm1zeWNyaEVlMnhCNWFha3lRdzNSV3dqR1oKb0Myb1E5VXBJRDd0UnNVK25jcmpkSWwvVXdhdGk1ZHQ2QnRpK1Jpa1dJRWwvc2k2MWtMSHlMcGNNOVJzVGlvKwp4TnM5dGNPMldtL0g1SFhnankwQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJURElTVW9scXVvdmpLUG1zcVg0dHFyWUt3QmVUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFjMkNlamk5TQpmQlA1TTJISFM2YTV5WFVIYU9jNHZYbXpOcGJCMSttZEsvYUtod1ZaajRXYWpFTFNLL3QvN3JKZndDVU9KY3hvCkQrSG9HaWJRTEdQd25xanpZK0wyS05EQlRSamx2UGxtNjlVN0E5bTVmeVJuMUN3bFVmcDZCeldpVm5mMFI3VmUKUkNlOG5vdGg4Q2xBSHlydURBdXo5bzZXUmN4aWJITEVGZnlKMnVLckRtZ0JXWXhaUXJYWEEyTDlxVG1lNUFqQwpjeUs0Q0dBK2ZLbVk0Q2FEeU1MaDF1blRzZ0ROaU1HOUQvWmxVS1N0Zi9JamxnU0EwS1ppNjNtWjk4TWhPRm91CmtqUGNNZGJHM1cwbHVWZGVSMzhLblBqUUVtTmxjS1A1ck56MWNKZ2kzVElNV0drS1dwYTQxZVFIRndaem0zOXAKNXdxWUpVMkRsVmQ1Q3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
current-context: my-context
users:
- name: my-user
  user:
    token: YOUR_ACCESS_TOKEN





